"use client";

import { FormEvent } from "react";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { toast } from "sonner";
import { Container } from "@/components/ui/container";

export default function ContactPage() {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); event.currentTarget.reset(); toast.success("Message received. We will reply soon."); }
  return <section className="py-14 lg:py-20"><Container><div className="mb-10"><p className="eyebrow">Support</p><h1 className="page-title">Let’s talk.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-white/45">Questions about sizing, delivery, bulk orders, or an existing order? Send us a message.</p></div><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-3">{[[MessageCircle,"WhatsApp","+880 1700-000000"],[Phone,"Call","01700-000000"],[Mail,"Email","hello@metalix.store"],[MapPin,"Based in","Dhaka, Bangladesh"]].map(([Icon,title,value]) => { const C = Icon as typeof MessageCircle; return <div key={String(title)} className="flex items-center gap-4 rounded-2xl border border-white/8 bg-white/[.025] p-5"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--accent)]/10 text-[var(--accent)]"><C size={19} /></span><div><p className="text-xs text-white/35">{String(title)}</p><p className="mt-1 font-semibold">{String(value)}</p></div></div>;})}</div><form onSubmit={submit} className="rounded-[2rem] border border-white/8 bg-white/[.025] p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="Your name" className="h-12 rounded-xl border border-white/10 bg-[#111113] px-4 text-sm outline-none focus:border-[var(--accent)]" /><input required type="email" placeholder="Email address" className="h-12 rounded-xl border border-white/10 bg-[#111113] px-4 text-sm outline-none focus:border-[var(--accent)]" /><input placeholder="Phone number" className="h-12 rounded-xl border border-white/10 bg-[#111113] px-4 text-sm outline-none focus:border-[var(--accent)] sm:col-span-2" /><textarea required placeholder="How can we help?" className="min-h-36 rounded-xl border border-white/10 bg-[#111113] p-4 text-sm outline-none focus:border-[var(--accent)] sm:col-span-2" /><button className="h-12 rounded-full bg-[var(--accent)] font-bold text-black sm:col-span-2">Send message</button></div></form></div></Container></section>;
}
